import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.config import get_settings
from app.models import Analysis, Document, RiskLevel

logger = logging.getLogger(__name__)
settings = get_settings()

RISK_COLORS = {
    RiskLevel.LOW: colors.HexColor("#22c55e"),
    RiskLevel.MEDIUM: colors.HexColor("#eab308"),
    RiskLevel.HIGH: colors.HexColor("#f97316"),
    RiskLevel.CRITICAL: colors.HexColor("#ef4444"),
}


class ReportGenerator:
    """Generate downloadable PDF compliance audit reports."""

    def generate_report(
        self,
        document: Document,
        analysis: Analysis,
        generated_by: str,
    ) -> str:
        settings.report_path.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now(UTC).strftime("%Y%m%d_%H%M%S")
        filename = f"compliance_report_{document.id}_{timestamp}.pdf"
        output_path = settings.report_path / filename

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=22,
            textColor=colors.HexColor("#1e3a5f"),
            spaceAfter=12,
            alignment=TA_CENTER,
        )
        heading_style = ParagraphStyle(
            "CustomHeading",
            parent=styles["Heading2"],
            fontSize=14,
            textColor=colors.HexColor("#1e3a5f"),
            spaceBefore=16,
            spaceAfter=8,
        )
        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            alignment=TA_JUSTIFY,
            spaceAfter=6,
        )
        small_style = ParagraphStyle(
            "Small",
            parent=styles["Normal"],
            fontSize=8,
            textColor=colors.grey,
        )

        story: list[Any] = []

        story.append(Paragraph("CompliancePilot AI", title_style))
        story.append(Paragraph("Compliance Audit Report", ParagraphStyle(
            "Subtitle", parent=styles["Normal"], fontSize=14, alignment=TA_CENTER, spaceAfter=20
        )))
        story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1e3a5f")))
        story.append(Spacer(1, 12))

        meta_data = [
            ["Document Title", document.title],
            ["Document Type", document.document_type.title()],
            ["Filename", document.filename],
            ["Analysis Date", analysis.created_at.strftime("%d %B %Y, %H:%M UTC")],
            ["Generated By", generated_by],
            ["Report ID", f"CP-{document.id}-{analysis.id}"],
        ]
        meta_table = Table(meta_data, colWidths=[2 * inch, 4.5 * inch])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 20))

        risk_level = analysis.risk_level
        risk_color = RISK_COLORS.get(risk_level, colors.grey)
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph(analysis.summary or "No summary available.", body_style))

        risk_data = [
            ["Risk Score", f"{analysis.risk_score:.0f} / 100"],
            ["Risk Level", risk_level.value.upper()],
            ["Total Findings", str(len(analysis.findings or []))],
            ["Processing Time", f"{analysis.processing_time_seconds:.1f}s"],
        ]
        risk_table = Table(risk_data, colWidths=[2 * inch, 4.5 * inch])
        risk_table.setStyle(TableStyle([
            ("BACKGROUND", (1, 1), (1, 1), risk_color),
            ("TEXTCOLOR", (1, 1), (1, 1), colors.white),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("PADDING", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(risk_table)
        story.append(Spacer(1, 16))

        if analysis.compliance_gaps:
            story.append(Paragraph("Compliance Gaps", heading_style))
            for gap in analysis.compliance_gaps:
                story.append(Paragraph(f"• {gap}", body_style))

        if analysis.findings:
            story.append(PageBreak())
            story.append(Paragraph("Detailed Findings", heading_style))
            for i, finding in enumerate(analysis.findings, 1):
                if isinstance(finding, dict):
                    severity = finding.get("severity", "medium").upper()
                    title = finding.get("title", f"Finding {i}")
                    category = finding.get("category", "General")
                    description = finding.get("description", "")
                    regulation = finding.get("regulation_reference", "N/A")
                    excerpt = finding.get("clause_excerpt", "")

                    story.append(Paragraph(
                        f"Finding {i}: {title}",
                        ParagraphStyle("FindingTitle", parent=styles["Heading3"], fontSize=11, spaceBefore=10)
                    ))
                    story.append(Paragraph(
                        f"<b>Category:</b> {category} | <b>Severity:</b> {severity} | "
                        f"<b>Regulation:</b> {regulation}",
                        body_style,
                    ))
                    story.append(Paragraph(description, body_style))
                    if excerpt:
                        story.append(Paragraph(
                            f'<i>Clause excerpt: "...{excerpt[:300]}..."</i>',
                            ParagraphStyle("Excerpt", parent=body_style, textColor=colors.HexColor("#64748b"))
                        ))

        if analysis.recommendations:
            story.append(Spacer(1, 16))
            story.append(Paragraph("Recommendations", heading_style))
            for i, rec in enumerate(analysis.recommendations, 1):
                story.append(Paragraph(f"{i}. {rec}", body_style))

        rag_sources = analysis.rag_sources or []
        if rag_sources:
            story.append(PageBreak())
            story.append(Paragraph("Regulatory References (RAG Sources)", heading_style))
            for source in rag_sources[:8]:
                if isinstance(source, dict):
                    story.append(Paragraph(
                        f"<b>{source.get('regulation', '')} — {source.get('section', '')}</b>",
                        body_style,
                    ))
                    story.append(Paragraph(source.get("content", "")[:400], body_style))
                    story.append(Paragraph(
                        f"Relevance: {source.get('relevance_score', 0):.0%} | Source: {source.get('source', '')}",
                        small_style,
                    ))
                    story.append(Spacer(1, 8))

        story.append(Spacer(1, 30))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        story.append(Paragraph(
            "This report was generated by CompliancePilot AI. It is intended for informational purposes "
            "and does not constitute legal advice. Consult qualified legal counsel for formal compliance certification.",
            small_style,
        ))
        story.append(Paragraph(
            f"© {datetime.now(UTC).year} CompliancePilot AI | Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
            small_style,
        ))

        doc.build(story)
        logger.info("Report generated: %s", output_path)
        return str(output_path)


report_generator = ReportGenerator()
